### ISSUE TITLE
resolution and styles

### ISSUE THREAD

**Issue by tomkralidis** [OGCMetOceanDWG/WorldWeatherSymbols#25]
Provide a different resolution, such as 100x100 or 20x20, or with optional styles encoded, or significant extra symbols added.

**Comment by chris-little** [comment]
@tomkralidis I think the above issue is actually three: 

1. Pixel orientated output at different resolutions;
2. Optional styling;
3. Accommodate many extra symbols.

**Comment by chris-little** [comment]
1. Is now covered by Issue #52 

2. Is now covered by Issue #53 

3. Is now covered by Issue #54
