### ISSUE TITLE
In symbols directories, add readmes with symbols

### ISSUE THREAD

**Issue by alexandreleroux** [OGCMetOceanDWG/WorldWeatherSymbols#30]
Here's a suggestion. If you agree that it's a good idea, I can implement.

The idea is to add readme.md files in each of the symbols directories, such as CH_CloudHigh, and display in the readme itself the symbols of the associated directory. This can be done by leveraging RawGit.com. 

Benefit: users would be able to see all symbols of a directory at once while browsing the GitHub repos instead of having to click all svg symbol individually to find out what they look like. Cheers -- Alex

**Comment by tomkralidis** [comment]
Great suggestion!  I can see this becoming a burden to manage over time if there are symbols added/deleted/renamed.

If you provide a Markdown template of how this would look, I'll put a script together which creates/places the `readme.md` files automagically.

**Comment by alexandreleroux** [comment]
Thanks Tom. Excellent suggestion. Automated magic is better than manual magic!

Possible workflow:
1. For every folder containing the WMO svg symbols:
2. Create a readme.md which would contain text + symbols, the text could be something similar to "Symbols of the $directoryname: $symbolname_n : displaysymbol_n" for all 'n' symbols in the folder, with a final note similar to "This readme.md is automatically generated by $linktoscript"
3. To display a symbol it needs to be referenced with the following URL: https://cdn.rawgit.com/OGCMetOceanDWG/WorldWeatherSymbols/master/Ft_Fronts/WeatherSymbol_WMO_Front_Cold_at_surface.svg while changing Ft_Fronts for the $folder and go through all the svgs in the folder

If that's not clear enough, let me know :) -- thanks

**Comment by alexandreleroux** [comment]
Closing, thanks @tomkralidis for the initial implementation
