### ISSUE TITLE
CC license version in symbols

### ISSUE THREAD

**Issue by KeeperOfMaps** [OGCMetOceanDWG/WorldWeatherSymbols#42]
Hello...

It appears that the intent of PR https://github.com/OGCMetOceanDWG/WorldWeatherSymbols/pull/39 was to update the license version to CC BY 4.0, however it looks like only the protocol in the URLs was changed from `http` to `https`. The license referenced in the SVG symbols is still CC-BY-3.0.

<img width="937" alt="Screen Shot 2022-09-30 at 9 44 49 AM" src="https://user-images.githubusercontent.com/110957686/193284869-c1f6a746-a825-488b-b257-a41cbb7bd55d.png">

**Comment by chris-little** [comment]
@tomkralidis I thnk this applies to every separate symbol file. Could you check please, because my offline copies seem to have disappeared from MS One Drive. Could we then create a global PR with a script? Also, I'm  sitting in a hotel room with jet lag :-(

**Comment by tomkralidis** [comment]
Thanks for the report! PR in #43
